### PR TITLE
Fixed deprecated features, added Linux support

### PR DESCRIPTION
**Pull request by MggMuggins**
This should make this package work again.

### CODE REVIEW

**Comment by MggMuggins** [comment]
I'm still working on the linux support. I'm sure it's something to do with the command stuff in the command lines. Hoping I can find out what is going on there and do something about it. If someone has more bash skills than I do, please let me know what I can do to fix it.

**Comment by MggMuggins** [comment]
8 hours later, I'm still trying to figure out how to get the file path. getPaths() does not work on my system, so i'm digging through the source for other people's stuff to try and understand how that is supposed to work. If anyone has any insights, or can make it work, please let me know. Or better yet, open a pull on my repo.

**Comment by MggMuggins** [comment]
Unless anyone else has anything to say about those methods and why they are returning undefined, I'm hanging up on this project for now.

**Comment by ysgard** [comment]
Hi @MggMuggins, thanks for the contrib!  I'll give this a quick test tonight and merge if there's no issues.

**Comment by MggMuggins** [comment]
My hope is there aren't. However, I still haven't gotten the Linux support to actually work...
This is because of an issue with the getPaths() method. Do you have any insight on this?

**Pull request merged**
